import {UUID} from 'crypto';

export type EventListener = (event: Event) => void;

export interface LatLonPosition {
    latitude: number;
    longitude: number;
}

export interface TimedLatLonPosition extends LatLonPosition {
    timestamp: number;
}

export interface ConnectorConfig {
    // Generated by the server. Vehicles reference connectors by it.
    id: UUID;
    name: string;
    connector: string;
    data: Record<string, string | number | boolean>;
}

export interface VehicleConfig {
    id: UUID;
    name: string;
    enabled: boolean;
    simulator: string;
    // speed, movementType and the simulator's position fields (see SIMULATOR_TYPES)
    data: Record<string, string | number | boolean | LatLonPosition>;
    connectors: UUID[];
}

export interface ConfigType {
    vehicles: VehicleConfig[];
    connectors: ConnectorConfig[];
}
