import {UUID} from 'crypto';

export type EventListener = (event: Event) => void;

export interface LatLonPosition {
    latitude: number;
    longitude: number;
}

export interface TimedLatLonPosition extends LatLonPosition {
    timestamp: number;
}

/** What a simulator is doing right now, for display in the web UI. */
export interface SimulatorDetails {
    phase: string;
    phaseStartedAt: number;
    // End of a waiting phase, or the estimated arrival while driving; null if unknown.
    phaseEndsAt: number | null;
    // Named places relevant to the current phase, e.g. the destination or the home station.
    places: Record<string, LatLonPosition>;
    stats: Record<string, string | number>;
    // The current wait is paused; `remainingMs` is what is left of it.
    paused: boolean;
    remainingMs: number | null;
    // Commands that control() accepts right now.
    controls: SimulatorAction[];
}

/** Commands to steer a running simulation from the web UI. */
export type SimulatorCommand =
    | {action: 'skipWait'}
    | {action: 'extendWait'; seconds: number}
    | {action: 'pauseWait'}
    | {action: 'resumeWait'}
    // null clears a previously set destination.
    | {action: 'setNextDestination'; position: LatLonPosition | null};

export type SimulatorAction = SimulatorCommand['action'];

export interface ConnectorConfig {
    // Generated by the server. Vehicles reference connectors by it.
    id: UUID;
    name: string;
    connector: string;
    data: Record<string, string | number | boolean>;
}

export interface VehicleConfig {
    id: UUID;
    name: string;
    enabled: boolean;
    simulator: string;
    // speed, movementType and the simulator's position fields (see SIMULATOR_TYPES)
    data: Record<string, string | number | boolean | LatLonPosition>;
    connectors: UUID[];
}

export interface ConfigType {
    vehicles: VehicleConfig[];
    connectors: ConnectorConfig[];
}
